### ISSUE TITLE
Conflict of pandas versions required by TUCAN vs. csd-python-api

### ISSUE THREAD

**Issue by schatzsc** [TUCAN-nest/TUCAN#100]
There is a conflict between the `pandas` versions required by TUCAN vs. the csd-python-api

After installation of csd-python-api, the TUCAN installation did not work anymore while an attempt to resolve this by a new installation of TUCAN lead to the following error message:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
csd-python-api 3.0.14 requires pandas<1.3, but you have pandas 1.5.2 which is incompatible.`

**Comment by JanCBrammer** [comment]
As @flange-ipb pointed out, `pandas` is a dependency of `networkx`.
With https://github.com/TUCAN-nest/TUCAN/commit/d9f6b399c97030f8f95d1654267907185ba0f686, we install `networkx` without dependencies, hence `pandas` won't be installed anymore when `tucan` is pip-installed.

See https://networkx.org/documentation/stable/release/migration_guide_from_2.x_to_3.0.html#default-dependencies.
