### ISSUE TITLE
print_molecule() from tucan.visualization produces error if run on non-canonicalized graph

### ISSUE THREAD

**Issue by schatzsc** [TUCAN-nest/TUCAN#111]
When `print_molecule()` from the `tucan.visualization` module is run on a graph that has not already been canonicalized an error message `KeyError: 'invariant_code'` is produced since the invariant codes are not assigned yet - this should be checked somehow and captures inside the routine

Steps to reproduce:

`from tucan.io.molfile_reader import graph_from_file`
`from tucan.visualization import print_molecule`
`mol = graph_from_file("any_molfile.mol")`
`print_molecule(mol)`

If `from tucan.canonicalization import canonicalize_molecule` is imported and `canon_mol = canonicalize_molecule(mol)` is run before the 3rd line above the error message does not show up

**Comment by flange-ipb** [comment]
I'm sorry, can't reproduce. The `invariant_code` node attribute is assigned to all atoms in the [graph_from_molecule](https://github.com/TUCAN-nest/TUCAN/blob/bliss-canonicalization/tucan/graph_utils.py#L23) function, which is called by the [molfile reader](https://github.com/TUCAN-nest/TUCAN/blob/bliss-canonicalization/tucan/io/molfile_reader.py#L64).

**Comment by schatzsc** [comment]
Strange - I had to install new CSD versions during the weekend, which also brought along a new python installation and re-installation of TUCAN on top of that following the instructions here and now the problem is gone on both my Windows 10 and Linux systems. Maybe an old or incomplete installation problem?!? Anyway, will close the issue
